import os
import json
import sqlite3
from datetime import datetime
from rich.console import Console

console = Console()

def process(state: dict) -> dict:
    console.print("[cyan]Finalizer Node[/cyan]: Exporting audit artifacts...")
    
    # Establish base paths
    exports_dir = "exports"
    os.makedirs(exports_dir, exist_ok=True)
    
    run_id = state.get("run_id", "Unknown")
    locale = state.get("locale", "en")
    
    # Variables for state tracking
    sqlite_saved = False
    json_export_path = ""
    markdown_report_path = ""
    streamlit_ready = False
    
    # 1. JSON Export
    try:
        json_file = os.path.join(exports_dir, f"geo_audit_{run_id}.json")
        with open(json_file, "w", encoding="utf-8") as f:
            json.dump(state, f, indent=4, ensure_ascii=False)
        json_export_path = json_file
        console.print(f"[green]Finalizer Node[/green]: JSON export saved to {json_export_path}")
    except Exception as e:
        console.print(f"[bold red]NODE_FAILED[/bold red]: JSON Export: {e}")

    # 2. SQLite Record
    try:
        db_path = "geo_audit.db"
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
        CREATE TABLE IF NOT EXISTS audits (
            run_id TEXT PRIMARY KEY,
            started_at TEXT,
            url TEXT,
            locale TEXT,
            target_industry TEXT,
            validation TEXT,
            roi_verified BOOLEAN
        )
        ''')
        
        cursor.execute('''
        INSERT OR REPLACE INTO audits 
        (run_id, started_at, url, locale, target_industry, validation, roi_verified)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (
            run_id,
            state.get("started_at", ""),
            state.get("url", ""),
            locale,
            state.get("target_industry", ""),
            state.get("validation", ""),
            state.get("roi_verified", False)
        ))
        
        conn.commit()
        conn.close()
        sqlite_saved = True
        console.print(f"[green]Finalizer Node[/green]: SQLite record saved to {db_path}")
    except Exception as e:
        console.print(f"[bold red]NODE_FAILED[/bold red]: SQLite Export: {e}")

    # 3. Branded Markdown Report
    try:
        md_file = os.path.join(exports_dir, f"geo_audit_{run_id}.md")
        
        # Determine labels based on locale
        if locale == "it":
            title = "Report Ufficiale Audit GEO"
            url_label = "URL Destinazione"
            ind_label = "Settore"
            aud_label = "Pubblico Principale"
            met_label = "Scalable Authority Matrix (v7.0)"
            ent_label = "Entity Consensus"
            info_label = "Information Gain"
            risk_label = "Trust & Grounding Score"
            cit_label = "Stato Citazioni"
            roi_label = "Proiezioni di Lift e Sostenibilità ROI"
            rec_label = "GEO Strategy: Recommendation Pack"
        else:
            title = "Official GEO Audit Report"
            url_label = "Target URL"
            ind_label = "Industry"
            aud_label = "Target Audience"
            met_label = "GEO Metrics"
            ent_label = "Entity Consensus"
            info_label = "Information Gain"
            risk_label = "Hallucination Risk"
            cit_label = "Citation Status"
            roi_label = "Lift Projection & ROI"
            rec_label = "GEO Recommendation Pack (Action Plan)"
            
        metrics = state.get("metrics", {})
            
        md_content = f"""# ☢️ NUCLEAR AI: {title}

**{url_label}:** {state.get("url", "N/A")}  
**Brand:** {state.get("brand_name", "N/A")} ({state.get("scale_level", "National")})  
**{ind_label}:** {state.get("target_industry", "N/A")}  
**{aud_label}:** {state.get("target_audience_summary", "N/A")}  

---

## 📊 {met_label}
- **{ent_label}:** {metrics.get("Entity Consensus", 0)}%
- **{info_label}:** {metrics.get("Information Gain", 0)}%
- **{risk_label}:** {100 - metrics.get("Hallucination Risk", 100)}% (Trust Verification)
- **{cit_label}:** {state.get("citation_status", "N/A")}

---

## 🚀 {roi_label}
- Lift: {state.get("projected_traffic_lift", "N/A")}
- ROI Verified: {"✅" if state.get("roi_verified") else "❌"}
- Note: {state.get("validator_notes", "")}

---

## 📋 {rec_label}
{state.get("geo_recommendation_pack", "N/A")}

---
*Report generated by Nuclear AI GEO Optimizer MVP on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*
"""
        with open(md_file, "w", encoding="utf-8") as f:
            f.write(md_content)
            
        markdown_report_path = md_file
        console.print(f"[green]Finalizer Node[/green]: Markdown report saved to {markdown_report_path}")
    except Exception as e:
        console.print(f"[bold red]NODE_FAILED[/bold red]: Markdown Export: {e}")

    # Set finalize state contract variables
    state["sqlite_saved"] = sqlite_saved
    state["json_export_path"] = json_export_path
    state["markdown_report_path"] = markdown_report_path
    
    if json_export_path:
        streamlit_ready = True
        
    state["streamlit_ready"] = streamlit_ready
    state["status"] = "Completed"

    console.print("[bold cyan]Finalizer Node[/bold cyan]: Run officially completed and artifacts securely saved.")

    return state
